import { requireMemberAccess, request, retainMemberSnapshot } from "../../services/api";
import { currentChromeStyle } from "../../services/layout";

type Message={id:string;sequence:number;senderType:"user"|"ai"|"admin"|"system";body:string;createdAt:string;senderLabel?:string};
type Conversation={id:string;status:"ai_active"|"waiting_human"|"human_active"|"resolved";version:number};
const labels={ai_active:"AI 助手",waiting_human:"等待客服",human_active:"人工处理中",resolved:"已解决"};
let pollTimer:ReturnType<typeof setInterval>|null=null;

Page({
 data:{chromeStyle:currentChromeStyle(),conversation:null as Conversation|null,messages:[] as Message[],latestCursor:0,olderCursor:null as number|null,statusLabel:"等待客服",input:"",sendAttempt:null as {id:string;body:string}|null,loading:true,loadingOlder:false,sending:false,handoffBusy:false,error:"",anchor:"",pageAlive:true},
 onLoad(){this.data.pageAlive=true;},onResize(){this.setData({chromeStyle:currentChromeStyle()});},
 onShow(){const preserve=retainMemberSnapshot(this);if(!preserve)this.setData({conversation:null,messages:[],latestCursor:0,olderCursor:null,input:"",sendAttempt:null,error:"",anchor:""});if(!requireMemberAccess("/pages/support/index"))return;this.data.pageAlive=true;void this.load();this.startPolling();},
 onHide(){this.stopPolling();},onUnload(){this.data.pageAlive=false;this.stopPolling();},
 startPolling(){this.stopPolling();pollTimer=setInterval(()=>void this.poll(),5000);},stopPolling(){if(pollTimer)clearInterval(pollTimer);pollTimer=null;},
 normalize(messages:Message[]){return messages.map(item=>({...item,senderLabel:item.senderType==="user"?"你":item.senderType==="admin"?"人工客服":item.senderType==="ai"?"AI 助手":"系统"}));},
 async load(){this.setData({loading:true,error:""});try{const page=await request<any>({path:"/v1/me/support/messages",cacheTags:["support"]});if(!this.data.pageAlive)return;const messages=this.normalize(page.messages||[]);this.setData({conversation:page.conversation,messages,latestCursor:page.latestCursor||0,olderCursor:page.olderCursor??null,statusLabel:page.conversation?labels[page.conversation.status as keyof typeof labels]:"等待客服",loading:false,anchor:messages.length?`support-${messages[messages.length-1]!.sequence}`:""});await this.markRead(messages);}catch{if(this.data.pageAlive)this.setData({loading:false,error:"客服会话暂时无法同步，请检查网络后重试。"});}},
 async poll(){if(!this.data.pageAlive||this.data.loading||this.data.sending||!this.data.conversation)return;try{const page=await request<any>({path:`/v1/me/support/messages?after=${this.data.latestCursor}&limit=50`,cacheTags:["support"]});if(!this.data.pageAlive)return;const fresh=this.normalize(page.messages||[]).filter((item:Message)=>item.sequence>this.data.latestCursor);if(fresh.length)this.append(fresh);if(page.conversation)this.setData({conversation:page.conversation,statusLabel:labels[page.conversation.status as keyof typeof labels]});await this.markRead(fresh);}catch{}},
 async loadOlder(){if(this.data.loadingOlder||this.data.olderCursor===null)return;const preserve=this.data.messages[0]?.sequence;this.setData({loadingOlder:true});try{const page=await request<any>({path:`/v1/me/support/messages?before=${this.data.olderCursor}&limit=50`,cacheTags:["support"]});if(!this.data.pageAlive)return;const older=this.normalize(page.messages||[]);this.setData({messages:[...older,...this.data.messages],olderCursor:page.olderCursor??null,anchor:preserve?`support-${preserve}`:""});}catch{wx.showToast({title:"更早消息暂时无法加载",icon:"none"});}finally{if(this.data.pageAlive)this.setData({loadingOlder:false});}},
 append(fresh:Message[]){const patch:Record<string,unknown>={latestCursor:fresh[fresh.length-1]!.sequence,anchor:`support-${fresh[fresh.length-1]!.sequence}`};const start=this.data.messages.length;fresh.forEach((item,index)=>patch[`messages[${start+index}]`]=item);this.setData(patch);},
 async markRead(messages:Message[]){const latest=[...messages].reverse().find(item=>item.senderType!=="user");if(!latest)return;try{await request({path:"/v1/me/support/read",method:"POST",data:{lastSeenSequence:this.data.latestCursor},cacheTags:["support"]});}catch{}},
 updateInput(event:WechatMiniprogram.TextareaInput){const input=event.detail.value;this.setData({input,sendAttempt:this.data.sendAttempt?.body===input.trim()?this.data.sendAttempt:null});},
 async send(){const body=this.data.input.trim();if(!body||this.data.sending)return;const sendAttempt=this.data.sendAttempt?.body===body?this.data.sendAttempt:{id:`wx-user-${Date.now()}-${Math.random().toString(36).slice(2,9)}`,body};this.setData({sending:true,error:"",sendAttempt});try{const result=await request<any>({path:"/v1/me/support/messages",method:"POST",data:{body,clientMessageId:sendAttempt.id},cacheTags:["support"]});if(!this.data.pageAlive)return;if(!this.data.messages.some(item=>item.id===result.message.id))this.append(this.normalize([result.message]));this.setData({input:"",sendAttempt:null,conversation:result.conversation,statusLabel:labels[result.conversation.status as keyof typeof labels]});}catch{if(this.data.pageAlive)this.setData({error:"消息没有确认送达，请保留文字并重试。"});}finally{if(this.data.pageAlive)this.setData({sending:false});}},
 async requestHuman(){if(this.data.handoffBusy)return;this.setData({handoffBusy:true,error:""});try{const conversation=await request<Conversation>({path:"/v1/me/support/handoff",method:"POST",data:{},cacheTags:["support"]});if(this.data.pageAlive)this.setData({conversation,statusLabel:labels[conversation.status]});}catch{if(this.data.pageAlive)this.setData({error:"暂时无法提交人工请求，请重试。"});}finally{if(this.data.pageAlive)this.setData({handoffBusy:false});}},
 retry(){void this.load();},back(){wx.navigateBack({fail:()=>wx.switchTab({url:"/pages/profile/index"})});}
});
