import { authorityProjection,hasCapability,requireCapability } from "../../services/authority";
import { request,retainMemberSnapshot } from "../../services/api";
import { currentChromeStyle } from "../../services/layout";
type Message={id:string;sequence:number;senderType:"user"|"ai"|"admin"|"system";body:string;senderLabel?:string};
const labels:Record<string,string>={waiting_human:"等待客服",human_active:"人工处理中",ai_active:"AI 助手",resolved:"已解决"};
let timer:ReturnType<typeof setInterval>|null=null;
Page({
 data:{chromeStyle:currentChromeStyle(),id:"",memberDisplayName:"CISME 会员",statusLabel:"同步中",conversation:null as any,messages:[] as Message[],latestCursor:0,olderCursor:null as number|null,assignedToMe:false,canAssign:false,canReply:false,canViewContext:false,aiStatus:"PROVIDER INTEGRATION PENDING",aiProviderAvailable:false,input:"",sendAttempt:null as {id:string;body:string}|null,loading:true,loadingOlder:false,busy:false,error:"",anchor:"",contextOpen:false,memberContext:null as any,pageAlive:true},
 onLoad(query:Record<string,string|undefined>){this.data.pageAlive=true;this.setData({id:query.id||""});},onResize(){this.setData({chromeStyle:currentChromeStyle()});},
 async onShow(){this.data.pageAlive=true;const preserve=retainMemberSnapshot(this);if(!preserve)this.setData({conversation:null,messages:[],latestCursor:0,olderCursor:null,assignedToMe:false,input:"",sendAttempt:null,contextOpen:false,memberContext:null});this.setData({loading:true});if(!await requireCapability("support.read"))return;const authority=await authorityProjection();this.setData({canAssign:hasCapability(authority,"support.assign"),canReply:hasCapability(authority,"support.reply"),canViewContext:hasCapability(authority,"member.support_view")});await Promise.all([this.load(),this.loadAiStatus()]);this.startPolling();},
 async loadAiStatus(){try{const status=await request<any>({path:"/v1/management/support/ai/status",cacheTags:["support"]});if(this.data.pageAlive)this.setData({aiStatus:status.status||"PROVIDER INTEGRATION PENDING",aiProviderAvailable:status.providerAvailable===true&&status.autoSendEnabled===false});}catch{if(this.data.pageAlive)this.setData({aiStatus:"PROVIDER INTEGRATION PENDING",aiProviderAvailable:false});}},
 onHide(){this.stopPolling();},onUnload(){this.data.pageAlive=false;this.stopPolling();},startPolling(){this.stopPolling();timer=setInterval(()=>void this.poll(),5000);},stopPolling(){if(timer)clearInterval(timer);timer=null;},
 normalize(messages:Message[]){return messages.map(item=>({...item,senderLabel:item.senderType==="user"?this.data.memberDisplayName:item.senderType==="admin"?"人工客服":item.senderType==="ai"?"AI 助手":"系统"}));},
 async load(){if(!this.data.id){this.setData({loading:false,error:"会话编号缺失。"});return;}this.setData({loading:true,error:""});try{const page=await request<any>({path:`/v1/management/support/conversations/${this.data.id}/messages`,cacheTags:["support"]});if(!this.data.pageAlive)return;this.data.memberDisplayName=page.memberDisplayName||"CISME 会员";const messages=this.normalize(page.messages||[]);this.setData({memberDisplayName:this.data.memberDisplayName,statusLabel:labels[page.conversation?.status]||"同步中",conversation:page.conversation,messages,latestCursor:page.latestCursor||0,olderCursor:page.olderCursor??null,assignedToMe:page.assignedToMe===true,loading:false,anchor:messages.length?`operator-${messages[messages.length-1]!.sequence}`:""});await this.markRead();}catch{if(this.data.pageAlive)this.setData({loading:false,error:"会话暂时无法同步，请重试。"});}},
 async poll(){if(!this.data.pageAlive||this.data.loading||this.data.busy||!this.data.conversation)return;try{const page=await request<any>({path:`/v1/management/support/conversations/${this.data.id}/messages?after=${this.data.latestCursor}&limit=50`,cacheTags:["support"]});if(!this.data.pageAlive)return;const fresh=this.normalize(page.messages||[]).filter((item:Message)=>item.sequence>this.data.latestCursor);if(fresh.length)this.append(fresh);this.setData({conversation:page.conversation,statusLabel:labels[page.conversation?.status]||"同步中",assignedToMe:page.assignedToMe===true});await this.markRead();}catch{}},
 async loadOlder(){if(this.data.loadingOlder||this.data.olderCursor===null)return;const preserve=this.data.messages[0]?.sequence;this.setData({loadingOlder:true});try{const page=await request<any>({path:`/v1/management/support/conversations/${this.data.id}/messages?before=${this.data.olderCursor}&limit=50`,cacheTags:["support"]});if(!this.data.pageAlive)return;const older=this.normalize(page.messages||[]);this.setData({messages:[...older,...this.data.messages],olderCursor:page.olderCursor??null,anchor:preserve?`operator-${preserve}`:""});}catch{wx.showToast({title:"更早消息暂时无法加载",icon:"none"});}finally{if(this.data.pageAlive)this.setData({loadingOlder:false});}},
 append(fresh:Message[]){const patch:Record<string,unknown>={latestCursor:fresh[fresh.length-1]!.sequence,anchor:`operator-${fresh[fresh.length-1]!.sequence}`};const start=this.data.messages.length;fresh.forEach((item,index)=>patch[`messages[${start+index}]`]=item);this.setData(patch);},
 async markRead(){if(!this.data.latestCursor)return;try{await request({path:`/v1/management/support/conversations/${this.data.id}/read`,method:"POST",data:{lastSeenSequence:this.data.latestCursor},cacheTags:["support"]});}catch{}},
 async claim(){if(!this.data.canAssign||this.data.busy||!this.data.conversation)return;this.setData({busy:true,error:""});try{const conversation=await request<any>({path:`/v1/management/support/conversations/${this.data.id}/claim`,method:"POST",data:{expectedVersion:this.data.conversation.version},cacheTags:["support"]});if(this.data.pageAlive)this.setData({conversation,statusLabel:labels[conversation.status],assignedToMe:true});}catch{if(this.data.pageAlive)this.setData({error:"接管失败，会话可能已被其他客服处理，请刷新。"});}finally{if(this.data.pageAlive)this.setData({busy:false});}},
 updateInput(event:WechatMiniprogram.TextareaInput){const input=event.detail.value;this.setData({input,sendAttempt:this.data.sendAttempt?.body===input.trim()?this.data.sendAttempt:null});},
 async suggest(){if(!this.data.aiProviderAvailable||!this.data.assignedToMe||this.data.busy)return;this.setData({busy:true,error:""});try{const draft=await request<any>({path:`/v1/management/support/conversations/${this.data.id}/suggested-reply`,method:"POST",data:{},cacheTags:["support"]});if(this.data.pageAlive)this.setData({input:String(draft.text||""),sendAttempt:null});}catch{if(this.data.pageAlive)this.setData({error:"AI 建议回复不可用，请继续人工处理。草稿不会自动发送。"});}finally{if(this.data.pageAlive)this.setData({busy:false});}},
 async send(){const body=this.data.input.trim();if(!body||!this.data.canReply||!this.data.assignedToMe||this.data.busy)return;const sendAttempt=this.data.sendAttempt?.body===body?this.data.sendAttempt:{id:`wx-agent-${Date.now()}-${Math.random().toString(36).slice(2,9)}`,body};this.setData({busy:true,error:"",sendAttempt});try{const result=await request<any>({path:`/v1/management/support/conversations/${this.data.id}/messages`,method:"POST",data:{body,clientMessageId:sendAttempt.id},cacheTags:["support"]});if(!this.data.pageAlive)return;if(!this.data.messages.some(item=>item.id===result.message.id))this.append(this.normalize([result.message]));this.setData({input:"",sendAttempt:null,conversation:result.conversation});}catch{if(this.data.pageAlive)this.setData({error:"回复未确认送达，请保留文字并重试。"});}finally{if(this.data.pageAlive)this.setData({busy:false});}},
 async resolve(){if(!this.data.canReply||!this.data.assignedToMe||this.data.busy||!this.data.conversation)return;const decision=await wx.showModal({title:"确认解决这次问题？",content:"会话历史会保留。用户再次发送消息时会重新进入待人工队列。",confirmText:"标记已解决"});if(!decision.confirm)return;this.setData({busy:true,error:""});try{const conversation=await request<any>({path:`/v1/management/support/conversations/${this.data.id}/resolve`,method:"POST",data:{expectedVersion:this.data.conversation.version},cacheTags:["support"]});if(this.data.pageAlive)this.setData({conversation,statusLabel:labels[conversation.status],assignedToMe:true});}catch{if(this.data.pageAlive)this.setData({error:"状态已变化，请刷新后再确认。"});}finally{if(this.data.pageAlive)this.setData({busy:false});}},
 async openContext(){if(!this.data.canViewContext||this.data.busy)return;this.setData({busy:true,error:""});try{const memberContext=await request<any>({path:`/v1/management/support/conversations/${this.data.id}/member-context`,method:"POST",data:{},cacheTags:["support"]});if(this.data.pageAlive)this.setData({memberContext,contextOpen:true});}catch{if(this.data.pageAlive)this.setData({error:"必要用户信息暂时无法读取或当前账号无权限。"});}finally{if(this.data.pageAlive)this.setData({busy:false});}},
 closeContext(){this.setData({contextOpen:false});},stopPropagation(){},retry(){void this.load();},back(){wx.navigateBack({fail:()=>wx.redirectTo({url:"/pages/management-support/index"})});}
});
