import { readFile, readdir } from "node:fs/promises";

const migrationFiles = (await readdir("db/migrations")).filter((file) => file.endsWith(".sql")).sort();
const migration = (await Promise.all(migrationFiles.map((file) => readFile(`db/migrations/${file}`, "utf8")))).join("\n");
const openapi = await readFile("openapi/openapi.yaml", "utf8");
const events = await readFile("docs/EVENT-CATALOG.md", "utf8");
const requiredTables = [
  "member_delivery_address", "member_profile", "privacy_request", "community_follow", "member_team_access", "upload_chunk", "member_contact", "phone_authorization", "legal_document", "member", "wechat_identity", "qualification_fact", "care_cycle", "care_cycle_pause", "care_record", "care_record_step", "eligibility_campaign", "eligibility_decision", "eligibility_task", "task_claim", "submission", "media_object", "media_cleanup_queue", "review_case", "appeal", "reward_claim", "points_grant", "points_lot", "points_entry", "points_projection", "points_action_request", "consent_grant", "revocation_request", "feed_item", "share_link", "share_visit", "share_attribution", "outbox_event", "audit_log",
  "data_retention_policy", "processing_purpose", "processor_registry", "consent_receipt", "legal_hold", "legal_hold_binding", "data_export_job", "data_erasure_job", "privacy_request_event",
  "ugc_post", "ugc_post_revision", "ugc_media_asset", "ugc_post_media", "ugc_comment", "ugc_report", "moderation_case", "moderation_action", "authority_grant", "support_conversation", "support_message", "support_operator_profile", "support_presence",
  "catalog_product", "catalog_sku", "catalog_price", "catalog_inventory_level", "catalog_qualification_decision", "catalog_inventory_adjustment",
  "commerce_checkout_quote", "commerce_order", "commerce_order_line", "commerce_order_address", "commerce_inventory_reservation", "commerce_order_transition"
];
const requiredPaths = ["/v1/me/addresses", "/v1/me/addresses/{addressId}", "/v1/me/addresses/{addressId}/default", "/v1/identity/capabilities", "/v1/me/profile", "/v1/team/member-profiles", "/v1/team/member-profiles/{memberId}/review", "/v1/me/privacy-requests", "/v1/admin/privacy-requests", "/v1/admin/privacy-requests/{requestId}/response", "/v1/admin/privacy-requests/{requestId}/execution-plan", "/v1/legal", "/v1/me/phone", "/v1/me/community-access", "/v1/me/follows", "/v1/me/following", "/v1/me/follows/{authorId}", "/v1/team/reviews", "/v1/team/publications", "/v1/team/submissions/{submissionId}/review", "/v1/team/submissions/{submissionId}/publish", "/v1/uploads/{mediaId}/chunks", "/v1/uploads/{mediaId}/assemble", "/v1/identity/dev", "/v1/identity/wechat", "/v1/care-cycles", "/v1/care-cycles/{cycleId}/activate", "/v1/care-cycles/{cycleId}/milestones/{milestone}/complete", "/v1/tasks/{taskId}/claim", "/v1/submissions/{submissionId}/draft", "/v1/submissions/{submissionId}/submit", "/v1/admin/tester-enrollments", "/v1/admin/campaigns", "/v1/admin/campaigns/{campaignId}", "/v1/admin/submissions/{submissionId}/review", "/v1/admin/submissions/{submissionId}/publish", "/v1/admin/points/grants", "/v1/admin/points/grants/{grantId}/actions", "/v1/admin/points/actions/{requestId}/approve", "/v1/admin/switches", "/v1/admin/worker-backlog", "/v1/admin/worker-failures", "/v1/admin/worker-failures/{queue}/{itemId}/redrive", "/v1/me/points", "/v1/feed", "/v1/shares/{shareId}/attributions/identity", "/v1/me/authority", "/v1/me/support/summary", "/v1/me/support/messages", "/v1/me/support/handoff", "/v1/me/support/read", "/v1/me/support/presence", "/v1/me/support/media/authorize", "/v1/me/support/media/{mediaId}/complete", "/v1/me/support/media/{mediaId}", "/v1/management/support/conversations", "/v1/management/support/conversations/{conversationId}/messages", "/v1/management/support/conversations/{conversationId}/claim", "/v1/management/support/conversations/{conversationId}/read", "/v1/management/support/conversations/{conversationId}/presence", "/v1/management/support/conversations/{conversationId}/media/{mediaId}", "/v1/management/support/conversations/{conversationId}/resolve", "/v1/management/support/conversations/{conversationId}/member-context", "/v1/management/support/conversations/{conversationId}/retention", "/v1/management/support/conversations/{conversationId}/purge"];
requiredPaths.push("/v1/catalog", "/v1/catalog/{productCode}", "/v1/management/catalog/products", "/v1/management/catalog/products/{productId}", "/v1/management/catalog/products/{productId}/qualification", "/v1/management/catalog/products/{productId}/publication", "/v1/management/catalog/skus/{skuId}/inventory-adjustments", "/v1/management/support/ai/status", "/v1/management/support/conversations/{conversationId}/suggested-reply");
requiredPaths.push("/v1/commerce/orders/status", "/v1/me/commerce/quotes", "/v1/me/orders", "/v1/me/orders/{orderId}", "/v1/me/orders/{orderId}/cancel", "/v1/management/commerce/orders", "/v1/management/commerce/orders/{orderId}");
const requiredEvents = ["identity.accepted.v1", "care.cycle.paused.v1", "care.cycle.resumed.v1", "care.cycle.terminated.v1", "care.milestone.completed.v1", "eligibility.decided.v1", "task.claimed.v1", "submission.reviewed.v1", "submission.publication.approved.v1", "reward.grant.created.v1", "points.grant.unfrozen.v1", "points.grant.expired.v1", "points.grant.reversed.v1", "consent.revocation.requested.v1", "share.identity.attributed.v1", "support.message.created.v1", "support.conversation.handoff_requested.v1", "support.conversation.claimed.v1", "support.conversation.resolved.v1", "support.conversation.purged.v1", "catalog.product.changed.v1", "catalog.product.qualified.v1", "catalog.product.publication_changed.v1", "catalog.inventory.adjusted.v1", "commerce.order.created.v1", "commerce.order.cancelled.v1", "commerce.order.expired.v1"];
const performancePaths = ["/v1/capabilities", "/v1/bootstrap/home", "/v1/bootstrap/profile", "/v1/bootstrap/settings", "/v1/feed/page", "/v1/feed/{postId}", "/v1/me/following/page", "/v1/admin/runtime-metrics"];
for (const table of requiredTables) if (!migration.includes(`CREATE TABLE ${table}`)) throw new Error(`MISSING_TABLE:${table}`);
for (const path of requiredPaths) if (!openapi.includes(path)) throw new Error(`MISSING_OPENAPI_PATH:${path}`);
for (const path of performancePaths) if (!openapi.includes(path)) throw new Error(`MISSING_OPENAPI_PATH:${path}`);
for (const event of requiredEvents) if (!events.includes(event)) throw new Error(`MISSING_EVENT:${event}`);
if (!migration.includes("UNIQUE(provider,app_id,openid)")) throw new Error("IDENTITY_PROVIDER_APP_OPENID_KEY_MISSING");
if (!migration.includes("media_object_current_kind_unique")) throw new Error("MEDIA_CURRENT_POINTER_MISSING");
if (!migration.includes("emergency_switch_formal_ugc_closed")) throw new Error("FORMAL_UGC_CLOSED_CONSTRAINT_MISSING");
if (!openapi.includes("feed_readonly: {type: boolean")) throw new Error("OPTIONAL_PUBLICATION_CONSENT_NOT_DOCUMENTED");
for (const [path, schema] of [["/v1/care-cycles/{cycleId}/activate", "CareVersionCommandInput"], ["/v1/care-cycles/{cycleId}/milestones/{milestone}/complete", "CareMilestoneCommandInput"]] as const) {
  const start = openapi.indexOf(`  ${path}:`);
  const end = openapi.indexOf("\n  /v1/", start + path.length + 3);
  const operation = openapi.slice(start, end === -1 ? openapi.length : end);
  if (!operation.includes("#/components/parameters/IdempotencyKey")) throw new Error(`CARE_COMMAND_IDEMPOTENCY_MISSING:${path}`);
  if (!operation.includes(`#/components/schemas/${schema}`)) throw new Error(`CARE_COMMAND_EXPECTED_VERSION_MISSING:${path}`);
}
if (!openapi.includes("CareVersionCommandInput: {type: object, additionalProperties: false, required: [expectedVersion]")) throw new Error("CARE_VERSION_COMMAND_SCHEMA_MISSING");
if (!openapi.includes("CareMilestoneCommandInput: {type: object, additionalProperties: false, required: [expectedVersion, stepCodes, selfAssessment]")) throw new Error("CARE_MILESTONE_DETAILS_SCHEMA_MISSING");
console.log(`${migrationFiles.length} migrations, ${requiredTables.length} tables, ${requiredPaths.length} paths and ${requiredEvents.length} events cross-checked`);
