import { authorityProjection, hasCapability, type AuthorityProjection } from "../../services/authority";
import { adjustInventory, centsToYuan, createProduct, managementProduct, packagedCatalogImages, parseYuanToCents, publishProduct, qualifyProduct, updateProduct, type CatalogProduct } from "../../services/commerce";
import { currentChromeStyle } from "../../services/layout";

function field(event:WechatMiniprogram.CustomEvent<{value:string}>):string{return event.detail.value;}
function problem(error:unknown):string{const candidate=error as {title?:string;message?:string};return candidate?.title||candidate?.message||"操作未完成，请检查后重试。";}

Page({
  dirty:false,
  data:{chromeStyle:currentChromeStyle(),authority:null as AuthorityProjection|null,id:"",product:null as CatalogProduct|null,loading:true,saving:false,dirty:false,error:"",name:"",code:"",subtitle:"",description:"",imagePath:packagedCatalogImages[0],skuCode:"",skuLabel:"",priceYuan:"",qualificationReason:"",qualificationEvidence:"",publicationReason:"",stockDelta:"",stockReason:"",canProduct:false,canQualify:false,canInventory:false,images:packagedCatalogImages},
  onResize(){this.setData({chromeStyle:currentChromeStyle()});},
  onLoad(query:Record<string,string|undefined>){this.setData({id:query.id??""});},
  async onShow(){try{const authority=await authorityProjection();const canProduct=hasCapability(authority,"commerce.product.manage");if(!canProduct&&!hasCapability(authority,"commerce.qualification.manage")&&!hasCapability(authority,"commerce.inventory.manage")){wx.showToast({title:"当前账号没有商品管理权限",icon:"none"});this.back();return;}this.setData({authority,canProduct,canQualify:hasCapability(authority,"commerce.qualification.manage"),canInventory:hasCapability(authority,"commerce.inventory.manage")});await this.load();}catch{this.setData({loading:false,error:"商品权限或详情暂时无法核验。所有写入保持关闭。"});}},
  onUnload(){if(this.dirty)wx.disableAlertBeforeUnload();},
  mark(values:WechatMiniprogram.IAnyObject){if(!this.dirty){this.dirty=true;wx.enableAlertBeforeUnload({message:"商品草稿尚未保存，确定离开吗？"});}this.setData({...values,dirty:true});},
  nameChange(e:WechatMiniprogram.CustomEvent<{value:string}>){this.mark({name:field(e)});},codeChange(e:WechatMiniprogram.CustomEvent<{value:string}>){this.mark({code:field(e)});},subtitleChange(e:WechatMiniprogram.CustomEvent<{value:string}>){this.mark({subtitle:field(e)});},descriptionChange(e:WechatMiniprogram.CustomEvent<{value:string}>){this.mark({description:field(e)});},skuCodeChange(e:WechatMiniprogram.CustomEvent<{value:string}>){this.mark({skuCode:field(e)});},skuLabelChange(e:WechatMiniprogram.CustomEvent<{value:string}>){this.mark({skuLabel:field(e)});},priceChange(e:WechatMiniprogram.CustomEvent<{value:string}>){this.mark({priceYuan:field(e)});},qualificationReasonChange(e:WechatMiniprogram.CustomEvent<{value:string}>){this.setData({qualificationReason:field(e)});},qualificationEvidenceChange(e:WechatMiniprogram.CustomEvent<{value:string}>){this.setData({qualificationEvidence:field(e)});},publicationReasonChange(e:WechatMiniprogram.CustomEvent<{value:string}>){this.setData({publicationReason:field(e)});},stockDeltaChange(e:WechatMiniprogram.CustomEvent<{value:string}>){this.setData({stockDelta:field(e)});},stockReasonChange(e:WechatMiniprogram.CustomEvent<{value:string}>){this.setData({stockReason:field(e)});},
  imageChange(e:WechatMiniprogram.CustomEvent<{value:number}>){this.mark({imagePath:packagedCatalogImages[Number(e.detail.value)]??packagedCatalogImages[0]});},
  async load(){if(!this.data.id){this.setData({loading:false,error:""});return;}this.setData({loading:true,error:""});try{const product=await managementProduct(this.data.id);const sku=product.variants[0];this.dirty=false;wx.disableAlertBeforeUnload();this.setData({product,loading:false,name:product.name,code:product.code,subtitle:product.subtitle,description:product.description,imagePath:(product.image||packagedCatalogImages[0]) as any,skuCode:sku?.code||"",skuLabel:sku?.label||"",priceYuan:sku?centsToYuan(sku.priceCents):"",dirty:false});}catch(error){this.setData({loading:false,error:problem(error)});}},
  payload(){const priceCents=parseYuanToCents(this.data.priceYuan);return {code:this.data.code,name:this.data.name,subtitle:this.data.subtitle,description:this.data.description,imagePath:this.data.imagePath,sku:{code:this.data.skuCode,label:this.data.skuLabel,priceCents}};},
  async save(){if(!this.data.canProduct||this.data.saving)return;let payload:WechatMiniprogram.IAnyObject;try{payload=this.payload();}catch{wx.showToast({title:"价格须为最多两位小数的人民币元",icon:"none"});return;}this.setData({saving:true});try{const current=this.data.product;const product=current?await updateProduct(current.productId,{...payload,expectedVersion:current.version,sku:{...(payload.sku as WechatMiniprogram.IAnyObject),id:current.variants[0]!.id,expectedVersion:current.variants[0]!.version,expectedPriceVersion:current.variants[0]!.priceVersion}}):await createProduct(payload);this.dirty=false;wx.disableAlertBeforeUnload();this.setData({id:product.productId,product,dirty:false});wx.showToast({title:"已由服务端保存",icon:"success"});await this.load();}catch(error){wx.showToast({title:problem(error),icon:"none"});}finally{this.setData({saving:false});}},
  async qualify(e:WechatMiniprogram.TouchEvent){if(!this.data.canQualify||!this.data.product||this.data.saving)return;const status=String(e.currentTarget.dataset.status);if(status==="eligible"&&!this.data.qualificationEvidence.trim()){wx.showToast({title:"确认可售须填写证据引用",icon:"none"});return;}this.setData({saving:true});try{const product=await qualifyProduct(this.data.product.productId,{expectedVersion:this.data.product.version,status,reason:this.data.qualificationReason,evidenceRef:this.data.qualificationEvidence});this.setData({product,qualificationReason:"",qualificationEvidence:""});wx.showToast({title:"资质状态已记录",icon:"success"});}catch(error){wx.showToast({title:problem(error),icon:"none"});}finally{this.setData({saving:false});}},
  async publication(e:WechatMiniprogram.TouchEvent){if(!this.data.canProduct||!this.data.product||this.data.saving)return;const action=String(e.currentTarget.dataset.action);this.setData({saving:true});try{const product=await publishProduct(this.data.product.productId,{expectedVersion:this.data.product.version,action,reason:this.data.publicationReason});this.setData({product,publicationReason:""});wx.showToast({title:action==="publish"?"已上架":"已下架",icon:"success"});}catch(error){wx.showToast({title:problem(error),icon:"none"});}finally{this.setData({saving:false});}},
  async inventory(){const product=this.data.product,sku=product?.variants[0];if(!this.data.canInventory||!sku||this.data.saving)return;if(!/^-?[1-9]\d*$/.test(this.data.stockDelta.trim())){wx.showToast({title:"库存调整须为非零整数",icon:"none"});return;}const delta=Number(this.data.stockDelta);if(!Number.isSafeInteger(delta)){wx.showToast({title:"库存调整超出范围",icon:"none"});return;}this.setData({saving:true});try{await adjustInventory(sku.id,{expectedVersion:sku.inventoryVersion,delta,reason:this.data.stockReason});this.setData({stockDelta:"",stockReason:""});wx.showToast({title:"库存已记录",icon:"success"});await this.load();}catch(error){wx.showToast({title:problem(error),icon:"none"});}finally{this.setData({saving:false});}},
  back(){wx.navigateBack({fail:()=>wx.redirectTo({url:"/pages/management-catalog/index"})});}
});
