import {afterEach,beforeEach,expect,it,vi} from 'vitest';
const m=vi.hoisted(()=>({request:vi.fn(),authority:vi.fn()}));
vi.mock('../../apps/miniprogram/services/api',()=>({request:m.request,requireMemberAccess:()=>true}));
vi.mock('../../apps/miniprogram/services/authority',()=>({authorityProjection:m.authority}));
vi.mock('../../apps/miniprogram/services/layout',()=>({currentChromeStyle:()=>''}));
vi.mock('../../apps/miniprogram/services/commerce-command-store',()=>({commerceContextRevision:()=>0}));
let def:any,token:string;
const record={id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',orderId:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',kind:'refund_only',state:'requested',version:1,amountCents:10000,reason:'合成原因',lines:[],resolved:false,refund:null};
beforeEach(()=>{vi.resetModules();vi.useFakeTimers();token='synthetic';m.request.mockReset().mockResolvedValue({items:[record],nextCursor:null});m.authority.mockReset().mockResolvedValue({version:1,managementAvailable:true,capabilities:['commerce.aftersale.review']});(globalThis as any).Page=(p:any)=>def=p;(globalThis as any).getApp=()=>({globalData:{sessionToken:token}});(globalThis as any).wx={showModal:vi.fn((o:any)=>o.success({confirm:true})),navigateBack:vi.fn(),redirectTo:vi.fn()};});
afterEach(()=>{vi.clearAllTimers();vi.useRealTimers();});
async function page(management=false){await import('../../apps/miniprogram/pages/aftersale/index');const p={...def,data:structuredClone(def.data),setData(p:any){Object.assign(this.data,p);}};p.onLoad({mode:management?'management':'',orderId:record.orderId});await p.onShow();return p;}
it('uses only server capabilities for management and keeps customer reads owner-scoped',async()=>{const p=await page();expect(p.data.coreReady).toBe(true);expect(m.authority).not.toHaveBeenCalled();expect(m.request.mock.calls[0]![0].path).toContain('/v1/me/aftersales?');const q=await page(true);expect(q.data.coreReady).toBe(true);expect(m.request.mock.calls.at(-1)![0].path).toContain('/v1/management/aftersales?');});
it('does not confuse returned stock, channel acceptance and verified refund success',async()=>{const p=await page(true);expect(p.normalize({...record,state:'refund_pending',refund:{submissionState:'accepted'},resolved:false}).label).toBe('退款处理中');expect(p.normalize({...record,resolved:true}).label).toContain('渠道核验成功');expect(p.selectActions({...record,state:'return_received',kind:'return_refund'})).toEqual([]);p.data.capabilities=['commerce.return.inspect'];expect(p.selectActions({...record,state:'return_received'})).toEqual([{action:'inspect_return',label:'记录质检结果'}]);});
it('uses the same key/payload after uncertainty and blocks duplicate submission',async()=>{const p=await page();p.data.basisIndex=6;p.data.note='原始合成说明';let reject!:(e:any)=>void;m.request.mockImplementationOnce(()=>new Promise((_,r)=>reject=r));const write=p.submit();await Promise.resolve();await p.submit();reject({status:504});await write;const original=structuredClone(p.pending);p.data.note='不能替换原请求';m.request.mockResolvedValueOnce(record).mockResolvedValueOnce({items:[record],nextCursor:null}).mockResolvedValueOnce(record);await p.submit();const writes=m.request.mock.calls.map(([x])=>x).filter(x=>x.method==='POST');expect(writes).toHaveLength(2);for(const w of writes){expect(w.idempotencyKey).toBe(original.key);expect(w.data.reason).toBe('原始合成说明');}});
it('clears private data and ignores late responses on hide',async()=>{const p=await page();let resolve!:(e:any)=>void;m.request.mockImplementationOnce(()=>new Promise(r=>resolve=r));p.data.note='合成私密说明';const load=p.load();p.onHide();resolve({items:[record],nextCursor:null});await load;expect(p.data.items).toEqual([]);expect(p.data.note).toBe('');expect(p.data.coreReady).toBe(false);});
it('requires fresh facts and explicit reconciliation after an interrupted request',async()=>{const p=await page();p.data.basisIndex=6;p.data.note='合成未确认操作';m.request.mockRejectedValueOnce({status:504});await p.submit();await p.reconcile();expect(p.pending).not.toBeNull();expect(p.data.notice).toContain('刷新');p.onHide();expect(p.pending).toBeNull();expect(p.data.needsReconcile).toBe(true);await p.onShow();p.data.note='新的申请';await p.submit();expect(m.request.mock.calls.filter(([x])=>x.method==='POST')).toHaveLength(1);await p.reconcile();expect(p.data.needsReconcile).toBe(false);expect(p.data.note).toBe('');});
it('revocation and session change erase case contacts and pending text',async()=>{const p=await page(true);p.data.selected={...record,returnDestination:{phone:'synthetic'}};p.data.note='private';m.authority.mockResolvedValueOnce({version:1,managementAvailable:false,capabilities:[]});await p.recheck();expect(p.data.selected).toBeNull();expect(p.data.note).toBe('');expect(p.data.coreReady).toBe(false);const q=await page();token='changed';await q.recheck();expect(q.data.items).toEqual([]);expect(q.data.coreReady).toBe(false);});
it('does not write after a modal returns to a different account',async()=>{const p=await page();p.data.basisIndex=6;p.data.note='合成审批说明';(globalThis as any).wx.showModal=(o:any)=>{token='another';o.success({confirm:true});};await p.submit();expect(m.request.mock.calls.some(([x])=>x.method==='POST')).toBe(false);});
