import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
const mocks=vi.hoisted(()=>({request:vi.fn(),authority:vi.fn()}));
vi.mock('../../apps/miniprogram/services/api',()=>({request:mocks.request}));
vi.mock('../../apps/miniprogram/services/authority',()=>({authorityProjection:mocks.authority,hasCapability:(a:any,c:string)=>a?.capabilities.includes(c)}));
vi.mock('../../apps/miniprogram/services/layout',()=>({currentChromeStyle:()=>''}));
vi.mock('../../apps/miniprogram/services/commerce-command-store',()=>({commerceContextRevision:()=>0}));
let definition:any,token:string;
const row={id:'synthetic-request',kind:'access',message:'Synthetic private request',status:'received',response:null,version:1,due_at:'2026-10-22T00:00:00Z',execution:null};
beforeEach(()=>{vi.resetModules();vi.useFakeTimers();token='synthetic-operator';mocks.request.mockReset();mocks.authority.mockReset().mockResolvedValue({version:1,managementAvailable:true,capabilities:['privacy.request.manage']});(globalThis as any).getApp=()=>({globalData:{sessionToken:token}});(globalThis as any).Page=(p:any)=>definition=p;(globalThis as any).wx={navigateBack:vi.fn(),redirectTo:vi.fn()};});
afterEach(()=>{vi.clearAllTimers();vi.useRealTimers();});
async function page(){await import('../../apps/miniprogram/pages/management-privacy/index');return {...definition,data:structuredClone(definition.data),setData(p:any){Object.assign(this.data,p);}};}
const select=(p:any)=>p.select({currentTarget:{dataset:{id:row.id}}});
describe('native privacy management lifecycle',()=>{
 it('clears sensitive rows and drafts on hide and rejects a late queue result',async()=>{const p=await page();let finish!:(x:any)=>void;mocks.request.mockImplementationOnce(()=>new Promise(r=>finish=r));const read=p.onShow();await Promise.resolve();p.onHide();finish([row]);await read;expect(p.data.items).toEqual([]);expect(p.data.selected).toBeNull();expect(p.data.response).toBe('');expect(p.data.coreReady).toBe(false);});
 it('shows only current capability data and clears it when a polling read is revoked',async()=>{const p=await page();mocks.request.mockResolvedValueOnce([row]);await p.onShow();select(p);p.onResponse({detail:{value:'private draft'}});mocks.request.mockRejectedValueOnce({status:403});await p.load(true);expect(p.data.items).toEqual([]);expect(p.data.response).toBe('');expect(p.data.coreReady).toBe(false);expect(p.timer).toBeNull();});
 it('never accepts an old account result after the session changes',async()=>{const p=await page();let finish!:(x:any)=>void;mocks.request.mockImplementationOnce(()=>new Promise(r=>finish=r));const read=p.onShow();await Promise.resolve();token='different-account';finish([row]);await read;expect(p.data.items).toEqual([]);expect(p.data.coreReady).toBe(false);});
 it('sends one versioned reply for repeated taps and refreshes the saved fact',async()=>{const p=await page();mocks.request.mockResolvedValueOnce([row]);await p.onShow();select(p);p.onResponse({detail:{value:'已受理，尚未执行导出。'}});let finish!:(x:any)=>void;mocks.request.mockImplementationOnce(()=>new Promise(r=>finish=r));const first=p.submit();await p.submit();const writes=mocks.request.mock.calls.filter(([x])=>x.method==='POST');expect(writes).toHaveLength(1);expect(writes[0]![0].data).toMatchObject({expectedVersion:1,status:'reviewing'});mocks.request.mockResolvedValueOnce([{...row,status:'reviewing',version:2}]);finish({version:2});await first;expect(p.data.busy).toBe(false);expect(p.data.selected).toBeNull();expect(p.data.items[0].version).toBe(2);});
 it('does not resubmit an uncertain reply and requires a fresh read before another action',async()=>{const p=await page();mocks.request.mockResolvedValueOnce([row]);await p.onShow();select(p);p.onResponse({detail:{value:'Test reply'}});mocks.request.mockRejectedValueOnce({status:504});await p.submit();await p.submit();expect(mocks.request.mock.calls.filter(([x])=>x.method==='POST')).toHaveLength(1);expect(p.data.coreReady).toBe(false);expect(p.data.actionError).toContain('刷新');});
 it('keeps approved execution facts read-only and refreshes version conflicts without another write',async()=>{const p=await page();mocks.request.mockResolvedValueOnce([{...row,status:'approved'}]);await p.onShow();select(p);await p.submit();expect(mocks.request.mock.calls.filter(([x])=>x.method==='POST')).toHaveLength(0);
 mocks.request.mockResolvedValueOnce([row]);await p.load();select(p);p.onResponse({detail:{value:'Stale reply'}});mocks.request.mockRejectedValueOnce({status:409});mocks.request.mockResolvedValueOnce([{...row,status:'responded',version:2}]);await p.submit();expect(mocks.request.mock.calls.filter(([x])=>x.method==='POST')).toHaveLength(1);expect(p.data.selected).toBeNull();expect(p.data.items[0].version).toBe(2);});
});
