import {afterEach,beforeEach,expect,it,vi} from 'vitest';
const m=vi.hoisted(()=>({request:vi.fn(),authority:vi.fn(),download:vi.fn(),release:vi.fn()}));
vi.mock('../../apps/miniprogram/services/api',()=>({request:m.request,downloadPrivateMedia:m.download}));
vi.mock('../../apps/miniprogram/services/authority',()=>({authorityProjection:m.authority,hasCapability:(a:any,c:string)=>a?.capabilities.includes(c)}));
vi.mock('../../apps/miniprogram/services/layout',()=>({currentChromeStyle:()=>''}));
vi.mock('../../apps/miniprogram/services/commerce-command-store',()=>({commerceContextRevision:()=>0}));
let def:any,token:string;
const rows='ORDER1\tSF\t顺丰\tSF12345\t2026-09-22T10:00:00.000Z';
beforeEach(()=>{vi.resetModules();vi.useFakeTimers();token='synthetic';m.request.mockReset().mockResolvedValue({items:[],nextCursor:null});m.authority.mockReset().mockResolvedValue({version:1,managementAvailable:true,capabilities:['commerce.fulfillment.manage']});m.release.mockReset();m.download.mockReset().mockReturnValue({promise:Promise.resolve('/tmp/synthetic.xlsx'),abort:m.release});(globalThis as any).getApp=()=>({globalData:{sessionToken:token}});(globalThis as any).Page=(p:any)=>def=p;(globalThis as any).wx={showModal:vi.fn((o:any)=>o.success({confirm:true})),openDocument:vi.fn((o:any)=>o.success()),navigateBack:vi.fn(),redirectTo:vi.fn()};});
afterEach(()=>{vi.clearAllTimers();vi.useRealTimers();});
async function page(){await import('../../apps/miniprogram/pages/management-fulfillment/index');return {...def,data:structuredClone(def.data),setData(p:any){Object.assign(this.data,p);}};}
it('fulfillment-only capability can load without order-read permission',async()=>{const p=await page();await p.onShow();expect(p.data.coreReady).toBe(true);expect(m.request).toHaveBeenCalledWith(expect.objectContaining({path:expect.stringContaining('/v1/management/shipments?')}));});
it('clears sensitive drafts and late responses after hiding',async()=>{const p=await page();let done!:(x:any)=>void;m.request.mockImplementationOnce(()=>new Promise(r=>done=r));const load=p.onShow();await Promise.resolve();p.data.rows=rows;p.onHide();done({items:[{id:'old'}],nextCursor:null});await load;expect(p.data.items).toEqual([]);expect(p.data.rows).toBe('');expect(p.data.coreReady).toBe(false);});
it('keeps the same immutable key for uncertain batch retries and blocks duplicate taps',async()=>{const p=await page();await p.onShow();p.data.rows=rows;p.data.confirmed=true;let fail!:(x:any)=>void;m.request.mockImplementationOnce(()=>new Promise((_,r)=>fail=r));const first=p.submit();await p.submit();fail({status:504});await first;const key=p.batchKey;expect(p.data.batchPending).toBe(true);p.newBatch();expect(p.batchKey).toBe(key);m.request.mockResolvedValueOnce({results:[{orderId:'synthetic',status:'accepted'}]});await p.submit();const writes=m.request.mock.calls.map(([x])=>x).filter(x=>x.method==='POST');expect(writes).toHaveLength(2);expect(writes.every(x=>x.idempotencyKey===key&&x.data.rows===rows)).toBe(true);expect(p.data.results[0].status).toBe('accepted');});
it('does not register malformed rows or unconfirmed dispatch',async()=>{const p=await page();await p.onShow();p.data.rows=rows;await p.submit();p.data.confirmed=true;p.data.rows='bad';await p.submit();expect(m.request.mock.calls.some(([x])=>x.method==='POST')).toBe(false);});
it('revocation after download prevents opening and cleans the private file',async()=>{const p=await page();await p.onShow();m.authority.mockResolvedValueOnce({version:1,managementAvailable:false,capabilities:[]});await p.exportExcel();expect((globalThis as any).wx.openDocument).not.toHaveBeenCalled();expect(m.release).toHaveBeenCalled();expect(p.data.coreReady).toBe(false);});
it('session change while foreground clears drafts and releases downloads on polling',async()=>{const p=await page();await p.onShow();await p.exportExcel();p.data.rows=rows;token='changed';await p.recheck();expect(p.data.rows).toBe('');expect(p.data.coreReady).toBe(false);expect(m.release).toHaveBeenCalled();});
it('shows per-row partial results without treating Excel as shipping truth',async()=>{const p=await page();await p.onShow();p.data.rows=rows;p.data.confirmed=true;m.request.mockResolvedValueOnce({results:[{orderId:'one',status:'accepted'},{orderId:'two',status:'rejected',code:'SHIPMENT_ALREADY_EXISTS'}]});await p.submit();expect(p.data.results).toHaveLength(2);expect(p.data.notice).toContain('微信同步');expect(p.data.batchPending).toBe(false);});
it('does not invent a new retry key after an uncertain request is interrupted by navigation',async()=>{const p=await page();await p.onShow();p.data.rows=rows;p.data.confirmed=true;m.request.mockRejectedValueOnce({status:504});await p.submit();p.onHide();m.request.mockResolvedValueOnce({items:[],nextCursor:null});await p.onShow();p.data.rows=rows;p.data.confirmed=true;await p.submit();expect(m.request.mock.calls.filter(([x])=>x.method==='POST')).toHaveLength(1);expect(p.data.notice).toContain('中断');await p.reconcileBatch();expect(p.data.batchPending).toBe(false);expect(p.data.rows).toBe('');});
